- name: launch an instance
  os_server:
    state: present
    #name: vm-jmanuel
    name: "{{ rhpropd_vmname }}"
    image: rhel-server-7.7-x86_64
    key_name: key_rhadmin
    timeout: 200
    flavor: m1.medium
    security_groups: default
    network: internal62
    floating_ip_pools: floating1062

